#ifndef OBJECT_H
#define OBJECT_H

enum Jubeta_ID {
    ID_BUTTON1,
    ID_BUTTON2,
    ID_BUTTON3,
    ID_BUTTON4,
    ID_BUTTON5,
    ID_BUTTON6,
    ID_BUTTON7,
    ID_BUTTON8,
    ID_BUTTON9,
    ID_BUTTON10,
    ID_BUTTON11,
    ID_BUTTON12,
    ID_BUTTON13,
    ID_BUTTON14,
    ID_BUTTON15,
    ID_BUTTON16,
    ID_SYNCTIMER,
    ID_JUBETA,
    ID_MUSIC,
    ID_MUSICBAR,
    ID_BACKGROUND,
    ID_INFORMATION
};

#endif
